a<-read.table("./a/household_power_consumption.txt",header = TRUE,sep = ";",na.strings = "?",nrows=300000)
b<- a[(a$Date == "1/2/2007"), ]
c<- a[(a$Date == "2/2/2007"), ]
d<-rbind(b,c)
par(mfrow = c(2,2) )
plot(strptime(paste(d[,"Date"],d[,"Time"]), "%d/%m/%Y %H:%M:%S"),d[,"Global_active_power"],type="l",xlab="",ylab="Global active power")
plot(strptime(paste(d[,"Date"],d[,"Time"]), "%d/%m/%Y %H:%M:%S"),d[,"Voltage"],type="l",xlab="datetime",ylab="Voltage")
plot(strptime(paste(d[,"Date"],d[,"Time"]), "%d/%m/%Y %H:%M:%S"),d[,"Sub_metering_1"],type="l",xlab="",ylab="Energy sub metering",)
points(strptime(paste(d[,"Date"],d[,"Time"]), "%d/%m/%Y %H:%M:%S"),d[,"Sub_metering_2"],type="l",xlab="",ylab="Energy sub metering",col="red")
points(strptime(paste(d[,"Date"],d[,"Time"]), "%d/%m/%Y %H:%M:%S"),d[,"Sub_metering_3"],type="l",xlab="",ylab="Energy sub metering",col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col=c(1,"red","blue"), lty=1,cex=0.3,xpd=TRUE,y=1,bty="n")
plot(strptime(paste(d[,"Date"],d[,"Time"]), "%d/%m/%Y %H:%M:%S"),d[,"Global_reactive_power"],type="l",xlab="datetime",ylab="Global_reactive_power")
library(datasets)
dev.copy(png,file="plot4.png")
dev.off()